name: Compliance Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1-5"

jobs:
    CyDig-Compliance-Workflow:
      uses: omegapoint/cydig-reusable-workflows/.github/workflows/compliance-template.yml@linnea-oxenwaldt-patch-1
      secrets: inherit
